export const urduDictionary: Record<string, string> = {
  "monk": "راهب",
  "mind": "دماغ",
  "focus": "توجہ",
  "summary": "خلاصہ",
  "blog": "بلاگ",
  "project": "پروجیکٹ",
  "idea": "خیال",
  "question": "سوال",
  "answer": "جواب",
  "example": "مثال",
  "solution": "حل",
  "problem": "مسئلہ",
  "work": "کام",
  "play": "کھیلنا",
  "learn": "سیکھنا",
  "teach": "پڑھانا",
  "write": "لکھنا",
  "read": "پڑھنا",
  "listen": "سننا",
  "speak": "بولنا",
  "think": "سوچنا",
  "understand": "سمجھنا",
  "create": "پیدا کرنا",
  "change": "تبدیل کرنا",
  "use": "استعمال کرنا",
  "help": "مدد کرنا",
  "i": "میں",
  "you": "آپ",
  "he": "وہ",
  "she": "وہ",
  "we": "ہم",
  "they": "وہ",
  "it": "یہ",
  "me": "مجھے",
  "my": "میرا",
  "your": "آپ کا",
  "his": "اس کا",
  "her": "اس کی",
  "our": "ہمارا",
  "their": "ان کا",
  "am": "ہوں",
  "is": "ہے",
  "are": "ہیں",
  "was": "تھا",
  "were": "تھے",
  "be": "ہونا",
  "have": "ہے",
  "has": "ہے",
  "do": "کرو",
  "did": "کیا",
  "can": "سکتا ہے",
  "will": "چاہے گا",
  "would": "چاہتا",
  "should": "چاہیے",
  "could": "سکتا تھا",
  "might": "شاید",
  "good": "اچھا",
  "bad": "برا",
  "happy": "خوش",
  "sad": "اداس",
  "new": "نیا",
  "old": "پرانا",
  "easy": "آسان",
  "difficult": "مشکل",
  "important": "اہم",
  "interesting": "دلچسپ",
  "beautiful": "خوبصورت",
  "ugly": "بدصورت",
  "fast": "تیز",
  "slow": "آہستہ",
  "strong": "مضبوط",
  "weak": "کمزور",
  "big": "بڑا",
  "small": "چھوٹا",
  "in": "میں",
  "on": "پر",
  "at": "پر",
  "to": "کو",
  "from": "سے",
  "with": "ساتھ",
  "without": "بغیر",
  "for": "کے لیے",
  "about": "کے بارے میں",
  "and": "اور",
  "but": "لیکن",
  "or": "یا",
  "if": "اگر",
  "then": "پھر",
  "because": "کیونکہ",
  "so": "تو",
  "while": "جبکہ",
  "until": "جب تک",
  "though": "اگرچہ",
  "although": "حالانکہ",
  "today": "آج",
  "yesterday": "کل",
  "tomorrow": "کل",
  "now": "اب",
  "later": "بعد میں",
  "before": "پہلے",
  "after": "بعد",
  "always": "ہمیشہ",
  "never": "کبھی نہیں",
  "sometimes": "کبھی کبھی",
  "often": "اکثر",
  "soon": "جلد",
  "early": "جلدی",
  "late": "دیر",
  "man": "آدمی",
  "woman": "عورت",
  "child": "بچہ",
  "boy": "لڑکا",
  "girl": "لڑکی",
  "friend": "دوست",
  "family": "خاندان",
  "person": "شخص",
  "people": "لوگ",
  "teacher": "استاد",
  "student": "طالب علم",
  "father": "والد",
  "mother": "والدہ",
  "brother": "بھائی",
  "sister": "بہن",
  "home": "گھر",
  "school": "اسکول",
  "office": "دفتر",
  "city": "شہر",
  "village": "گاؤں",
  "country": "ملک",
  "market": "بازار",
  "hospital": "ہسپتال",
  "road": "سڑک",
  "room": "کمرہ",
  "air": "ہوا",
  "water": "پانی",
  "food": "کھانا",
  "money": "پیسہ",
  "fire": "آگ",
  "earth": "زمین",
  "light": "روشنی",
  "dark": "اندھیرا",
  "color": "رنگ",
  "blue": "نیلا",
  "red": "سرخ",
  "green": "سبز",
  "yellow": "پیلا",
  "black": "کالا",
  "white": "سفید",
  "time": "وقت",
  "day": "دن",
  "night": "رات",
  "week": "ہفتہ",
  "month": "مہینہ",
  "year": "سال",
  "thank you": "شکریہ",
  "good morning": "صبح بخیر",
  "good night": "شب بخیر",
  "how are you": "آپ کیسے ہیں",
  "i am fine": "میں ٹھیک ہوں",
  "see you": "پھر ملیں گے",
  "himself": "خود",
  "mild": "ہلکا",
  "summer-cool": "گرمیوں کی ٹھنڈک",
  "weather": "موسم",
  "latitudes": "عرض البلد",
  "preparation": "تیاری",
  "active": "سرگرم",
  "pursuits": "مصروفیات",
  "shortly": "جلد",
  "perth": "پرتھ",
  "begrimed": "میلا",
  "blistered": "چھالوں والا",
  "blacksmith": "لوہار",
  "removed": "ہٹایا",
  "portable": "لے جانے کے قابل",
  "forge": "بھٹی",
  "hold": "تھامنا",
  "again": "دوبارہ",
  "concluding": "اختتام",
  "contributory": "معاون",
  "leg": "ٹانگ",
  "still": "اب بھی",
  "retained": "رکھا",
  "deck": "عرشہ",
  "lashed": "باندھا",
  "ringbolts": "رِنگ بولٹ",
  "foremast": "سامنے کا مستول",
  "almost": "تقریباً",
  "incessantly": "مسلسل",
  "invoked": "پکارا گیا",
  "headsmen": "سربراہ",
  "harpooneers": "ہارپون پھینکنے والے",
  "bowsmen": "کشتی کے اگلے حصے کے ملاح",
  "some": "کچھ",
  "little": "چھوٹا",
  "job": "کام",
  "altering": "تبدیل کرنا",
  "repairing": "مرمت کرنا",
  "shaping": "شکل دینا",
  "various": "مختلف",
  "weapons": "ہتھیار",
  "boat": "کشتی",
  "furniture": "سامان",
  "eager": "بے تاب",
  "circle": "گھیرہ",
  "waiting": "انتظار",
  "served": "خدمت کی گئی",
  "holding": "پکڑے ہوئے",
  "boat-spades": "کشتی کے بیلچے",
  "pike-heads": "برچھی کے سرے",
  "harpoons": "ہارپون",
  "lances": "برچھیاں",
  "watching": "دیکھنا",
  "every": "ہر",
  "sooty": "کالا",
  "movement": "حرکت",
  "patient": "بردبار",
  "hammer": "ہتھوڑا",
  "arm": "بازو",
  "reigned": "راج کرنا",
  "anticipated": "متوقع",
  "peculiarly": "غیر معمولی طور پر",
  "surrounded": "گھرا ہوا",
  "jealously": "حسد سے",
  "toiled": "محنت کی",
  "wielded": "چلایا",
  "welcome": "خوش آمدید"
};

export function translateToUrdu(text: string): string {
  return text
    .split(" ")
    .map((word) => {
      const clean = word.toLowerCase().replace(/[^\w-]/g, "");
      const translation = urduDictionary[clean] || word;
      const punctuation = word.match(/[.,!?]$/);
      return punctuation ? translation + punctuation[0] : translation;
    })
    .join(" ");
}
